import { LeaderboardEntry, AutomatedEvaluationEntry } from './types';

// IMPORTANT: This path must match the 'base' property in vite.config.ts.
// It's used for client-side routing to fix an issue where import.meta.env.BASE_URL
// is not available in the execution environment.
export const BASE_PATH = '/leaderboard/';

const modelWebsites: { [key: string]: string } = {
  'Motion capture': 'https://pantomatrix.github.io/EMAGE/',
  'ConvoFusion': 'https://vcai.mpi-inf.mpg.de/projects/ConvoFusion/',
  'RAG-Gesture': 'https://vcai.mpi-inf.mpg.de/projects/RAG-Gesture/',
  'HoloGest': 'https://cyk990422.github.io/HoloGest.github.io/',
  'Semantic Gesticulator': 'https://pku-mocca.github.io/Semantic-Gesticulator-Page/',
  'AMUSE': 'https://amuse.is.tue.mpg.de/',
  'Seamless': 'https://ai.meta.com/research/seamless-interaction/'
};

const modelCodeRepos: { [key: string]: string } = {
  'Semantic Gesticulator': 'https://github.com/LuMen-ze/Semantic-Gesticulator-Official',
  'ConvoFusion': 'https://github.com/m-hamza-mughal/convofusion',
  'DiffuseStyleGesture': 'https://github.com/YoungSeng/DiffuseStyleGesture',
  'RAG-Gesture': 'https://github.com/m-hamza-mughal/RAG-Gesture',
  'AMUSE': 'https://github.com/kiranchhatre/amuse'
};

export { modelCodeRepos };

export const LEADERBOARD_DATA: LeaderboardEntry[] = [
  {
    rank: 0,
    modelName: 'Seamless',
    motionRealismElo: 1112,
    motionRealismEloCI: [1094, 1130],
    speechGestureAlignmentPercentage: 75.1,
    speechGestureAlignmentPercentageCI: [71.4, 78.7],
    websiteUrl: modelWebsites['Seamless'],
    systemDetailsUrl: 'TODO',
    trainingHours: 3950,
  },
  {
    rank: 1,
    modelName: 'Motion capture',
    motionRealismElo: 1118,
    motionRealismEloCI: [1100, 1136],
    speechGestureAlignmentPercentage: 73.9,
    speechGestureAlignmentPercentageCI: [71.2, 76.5],
    websiteUrl: modelWebsites['Motion capture'],
    // reference data; not a trained model
  },
  {
    rank: 2,
    modelName: 'ConvoFusion',
    motionRealismElo: 1084,
    motionRealismEloCI: [1071, 1097],
    speechGestureAlignmentPercentage: 49.5,
    speechGestureAlignmentPercentageCI: [46.7, 52.2],
    websiteUrl: modelWebsites['ConvoFusion'],
    trainingHours: 25,
    venue: 'CVPR',
    year: 2024,
  },
  {
    rank: 3,
    modelName: 'RAG-Gesture',
    motionRealismElo: 1066,
    motionRealismEloCI: [1052, 1080],
    speechGestureAlignmentPercentage: 49.1,
    speechGestureAlignmentPercentageCI: [46.2, 52.1],
    websiteUrl: modelWebsites['RAG-Gesture'],
    trainingHours: 25,
    venue: 'CVPR',
    year: 2025,
  },
  {
    rank: 4,
    modelName: 'HoloGest',
    motionRealismElo: 1064,
    motionRealismEloCI: [1049, 1078],
    speechGestureAlignmentPercentage: 60.0,
    speechGestureAlignmentPercentageCI: [57.3, 62.6],
    websiteUrl: modelWebsites['HoloGest'],
    trainingHours: 25,
    venue: '3DV',
    year: 2025,
  },
  {
    rank: 5,
    modelName: 'Semantic Gesticulator',
    motionRealismElo: 1056,
    motionRealismEloCI: [1042, 1070],
    speechGestureAlignmentPercentage: 57.3,
    speechGestureAlignmentPercentageCI: [54.5, 60.0],
    websiteUrl: modelWebsites['Semantic Gesticulator'],
    trainingHours: 25,
    venue: 'SIGGRAPH',
    year: 2024,
  },
  {
    rank: 6,
    modelName: 'AMUSE',
    motionRealismElo: 818,
    motionRealismEloCI: [785, 849],
    speechGestureAlignmentPercentage: 51.8,
    speechGestureAlignmentPercentageCI: [48.8, 54.6],
    websiteUrl: modelWebsites['AMUSE'],
    trainingHours: 25,
    venue: 'CVPR',
    year: 2024,
  },
  {
    rank: 7,
    modelName: 'DiffuseStyleGesture',
    motionRealismElo: 684,
    motionRealismEloCI: [641, 723],
    speechGestureAlignmentPercentage: 60.9,
    speechGestureAlignmentPercentageCI: [58.1, 63.7],
    websiteUrl: modelWebsites['DiffuseStyleGesture'],
    trainingHours: 25,
    venue: 'IJCAI',
    year: 2023,
  },
];

export const AUTOMATED_EVALUATION_DATA: AutomatedEvaluationEntry[] = [
  {
    modelName: 'Motion capture',
    fgd: 0,
    ba: 0.645,
    srgr: 1,
    divPose: 8.302,
    divSample: null,
    websiteUrl: modelWebsites['Motion capture'],
  },
  {
    modelName: 'Seamless',
    fgd: 4.743,
    ba: 0.626,
    srgr: 0.348,
    divPose: 6.908,
    divSample: 0.022,
    websiteUrl: modelWebsites['Seamless'],
  },
  {
    modelName: 'HoloGest',
    fgd: 0.625,
    ba: 0.539,
    srgr: 0.469,
    divPose: 7.733,
    divSample: 0.011,
    websiteUrl: modelWebsites['HoloGest'],
    venue: '3DV',
    year: 2025,
  },
  {
    modelName: 'ConvoFusion',
    fgd: 0.6,
    ba: 0.611,
    srgr: 0.448,
    divPose: 8.911,
    divSample: 0.013,
    websiteUrl: modelWebsites['ConvoFusion'],
    venue: 'CVPR',
    year: 2024,
  },
  {
    modelName: 'RAG-Gesture',
    fgd: 0.515,
    ba: 0.648,
    srgr: 0.427,
    divPose: 10.092,
    divSample: 0.013,
    websiteUrl: modelWebsites['RAG-Gesture'],
    venue: 'CVPR',
    year: 2025,
  },
  {
    modelName: 'Semantic Gesticulator',
    fgd: 0.473,
    ba: 0.681,
    srgr: 0.398,
    divPose: 10.993,
    divSample: 0.02,
    websiteUrl: modelWebsites['Semantic Gesticulator'],
    venue: 'SIGGRAPH',
    year: 2024,
  },
  {
    modelName: 'AMUSE',
    fgd: 0.785,
    ba: 0.757,
    srgr: 0.394,
    divPose: 9.552,
    divSample: 0.018,
    websiteUrl: modelWebsites['AMUSE'],
    venue: 'CVPR',
    year: 2024,
  },
  {
    modelName: 'DiffuseStyleGesture',
    fgd: 7.11,
    ba: 0.608,
    srgr: 0.312,
    divPose: 9.598,
    divSample: 0.001,
    websiteUrl: modelWebsites['DiffuseStyleGesture'],
    venue: 'IJCAI',
    year: 2023,
  },
];