import { LeaderboardEntry, AutomatedEvaluationEntry } from './types';

// IMPORTANT: This path must match the 'base' property in vite.config.ts.
// It's used for client-side routing to fix an issue where import.meta.env.BASE_URL
// is not available in the execution environment.
export const BASE_PATH = '/leaderboard/';

const modelWebsites: { [key: string]: string } = {
  'Motion capture': 'https://pantomatrix.github.io/EMAGE/',
  'ConvoFusion': 'https://vcai.mpi-inf.mpg.de/projects/ConvoFusion/',
  'RAG-Gesture': 'https://vcai.mpi-inf.mpg.de/projects/RAG-Gesture/',
  'HoloGest': 'https://cyk990422.github.io/HoloGest.github.io/',
  'Semantic Gesticulator': 'https://pku-mocca.github.io/Semantic-Gesticulator-Page/',
  'AMUSE': 'https://amuse.is.tue.mpg.de/',
  'DiffuseStyleGesture': 'https://github.com/YoungSeng/DiffuseStyleGesture',
};

export const LEADERBOARD_DATA: LeaderboardEntry[] = [
  {
    rank: 1,
    modelName: 'Motion capture',
    motionRealismElo: 1133,
    motionRealismEloCI: [1111, 1155],
    speechGestureAlignmentPercentage: 73.7,
    speechGestureAlignmentPercentageCI: [71, 76],
    websiteUrl: modelWebsites['Motion capture'],
  },
  {
    rank: 2,
    modelName: 'ConvoFusion',
    motionRealismElo: 1102,
    motionRealismEloCI: [1087, 1117],
    speechGestureAlignmentPercentage: 49.7,
    speechGestureAlignmentPercentageCI: [47, 52],
    websiteUrl: modelWebsites['ConvoFusion'],
    venue: 'CVPR',
    year: 2024,
  },
  {
    rank: 3,
    modelName: 'RAG-Gesture',
    motionRealismElo: 1088,
    motionRealismEloCI: [1072, 1104],
    speechGestureAlignmentPercentage: 48.9,
    speechGestureAlignmentPercentageCI: [46, 52],
    websiteUrl: modelWebsites['RAG-Gesture'],
    venue: 'CVPR',
    year: 2025,
  },
  {
    rank: 4,
    modelName: 'HoloGest',
    motionRealismElo: 1082,
    motionRealismEloCI: [1065, 1098],
    speechGestureAlignmentPercentage: 59.7,
    speechGestureAlignmentPercentageCI: [57, 62],
    websiteUrl: modelWebsites['HoloGest'],
    venue: '3DV',
    year: 2025,
  },
  {
    rank: 5,
    modelName: 'Semantic Gesticulator',
    motionRealismElo: 1072,
    motionRealismEloCI: [1056, 1088],
    speechGestureAlignmentPercentage: 56.6,
    speechGestureAlignmentPercentageCI: [54, 59],
    websiteUrl: modelWebsites['Semantic Gesticulator'],
    venue: 'SIGGRAPH',
    year: 2024,
  },
  {
    rank: 6,
    modelName: 'AMUSE',
    motionRealismElo: 825,
    motionRealismEloCI: [788, 860],
    speechGestureAlignmentPercentage: 52.2,
    speechGestureAlignmentPercentageCI: [49, 55],
    websiteUrl: modelWebsites['AMUSE'],
    venue: 'CVPR',
    year: 2024,
  },
  {
    rank: 7,
    modelName: 'DiffuseStyleGesture',
    motionRealismElo: 701,
    motionRealismEloCI: [654, 743],
    speechGestureAlignmentPercentage: 60.3,
    speechGestureAlignmentPercentageCI: [58, 63],
    websiteUrl: modelWebsites['DiffuseStyleGesture'],
    venue: 'IJCAI',
    year: 2023,
  },
];

export const AUTOMATED_EVALUATION_DATA: AutomatedEvaluationEntry[] = [
  {
    modelName: 'Motion capture',
    fgd: 0,
    ba: 0.645,
    srgr: 1,
    divPose: 8.302,
    divSample: null,
    websiteUrl: modelWebsites['Motion capture'],
  },
  {
    modelName: 'HoloGest',
    fgd: 0.625,
    ba: 0.539,
    srgr: 0.469,
    divPose: 7.733,
    divSample: 0.011,
    websiteUrl: modelWebsites['HoloGest'],
    venue: '3DV',
    year: 2025,
  },
  {
    modelName: 'ConvoFusion',
    fgd: 0.6,
    ba: 0.611,
    srgr: 0.448,
    divPose: 8.911,
    divSample: 0.013,
    websiteUrl: modelWebsites['ConvoFusion'],
    venue: 'CVPR',
    year: 2024,
  },
  {
    modelName: 'RAG-Gesture',
    fgd: 0.515,
    ba: 0.648,
    srgr: 0.427,
    divPose: 10.092,
    divSample: 0.013,
    websiteUrl: modelWebsites['RAG-Gesture'],
    venue: 'CVPR',
    year: 2025,
  },
  {
    modelName: 'Semantic Gesticulator',
    fgd: 0.473,
    ba: 0.681,
    srgr: 0.398,
    divPose: 10.993,
    divSample: 0.02,
    websiteUrl: modelWebsites['Semantic Gesticulator'],
    venue: 'SIGGRAPH',
    year: 2024,
  },
  {
    modelName: 'AMUSE',
    fgd: 0.785,
    ba: 0.757,
    srgr: 0.394,
    divPose: 9.552,
    divSample: 0.018,
    websiteUrl: modelWebsites['AMUSE'],
    venue: 'CVPR',
    year: 2024,
  },
  {
    modelName: 'DiffuseStyleGesture',
    fgd: 7.11,
    ba: 0.608,
    srgr: 0.312,
    divPose: 9.598,
    divSample: 0.001,
    websiteUrl: modelWebsites['DiffuseStyleGesture'],
    venue: 'IJCAI',
    year: 2023,
  },
];